/**:
  ros__parameters:
    robot_description_kinematics:
      rizon_arm:
        kinematics_solver: pick_ik/PickIkPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.05
