publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "rizon_arm_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2"]
    pos1: [-1.40, -0.70, 0.00, 1.57, 0.01, 0.69, 0.00]
    pos2: [-1.40, -0.70, 0.00, 1.57, 0.01, 0.69, 0.00]

    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7

    check_starting_point: true
